apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: ""   # are i fill this at deploy time with the Atlas URI
  DOCKERHUB_USER: ""   # optional, for pulling/pushing private images
  DOCKERHUB_TOKEN: ""  # optiona×ª DockerHub access token